#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 23 10:20:28 2020

@author: zhuxinyan
"""

math=input("输入数学成绩： ")
eng=input("输入英文成绩： ")
math=input(math)
eng=input(eng)


if (math >= 90 and eng >= 90):
    print('得到奖品')

elif (math < 60 and eng < 60):
    print("要处罚")

elif (math < 60 or eng < 60):
    print('再加油')

else:
    print('pass')








