#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 15 11:14:09 2020

@author: zhuxinyan
"""

import random
for i in range(1,10):
    for j in range(1,10):
        print(i,"x",j,"=",i*j)














