#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 24 11:06:29 2020

@author: zhuxinyan
"""


import pygame
x=(56,67,88)
y=(24,47,86)

size = (800,600)

screen = pygame.display.set_mode(size)
pygame.display.set_caption("apple")
done = False
clock = pygame.time.Clock()
screen.fill(y)
size = (50,50)
r = pygame.Surface(size)
pygame.draw.rect(screen,x, r.get_rect(),50)
pygame.display.flip()
clock.tick



