#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 24 10:29:10 2020

@author: zhuxinyan
"""


import random

count = 0

a = random.randint(1,10)

while count<5 :
    count+=1    
    x = input("请输入1～10")
    x = int(x)

    if a>x :
        if count==5:
            print ("5")
        else :
            print("太小")

    elif x>a :
        if count==5:
            print ("5")
        else :
            print("太大")
    
    else :
        if count==5:
            print ("5")
        else :
            print("正确")
            break







