#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 31 11:41:36 2020

@author: zhuxinyan
"""











import pygame,random

red=(255,0,0)
orange1=(255,153,0)
orange2=(255,130,0)
brown=(128,42,42)
black=(0,0,0)
white=(255,255,255)
def recursive_draw (x,y,w,h):
    pygame.draw.rect(screen.white,[x,y,w,h],1)
    #pygame.draw.circle(画布，颜色，[x,y,w,h],线宽) 
    if ( w > 14 ):
        x += w * .1
        y += h * .1
        w *= .8
        h *= .8
        recursive_draw(x, y, w, h)


pygame.init()
size=(1000,1000)
screen=pygame.display.set_mode(size)

pygame.display.set_caption("apple")

x=False
clock=pygame.time.Clock()

while not x:
    
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            x=True
        screen.fill(black)
    recursive_draw(0,0,700,500)
    pygame.display.flip()
    clock.tick(60)

pygame.quit()







