#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov  7 10:15:24 2020

@author: zhuxinyan
"""


import pygame,random

black=(0,0,0)

def colors ():
    r=random .randint(0,255)
    g=random .randint(0,255)
    b=random .randint(0,255)
    return (r,g,b)

size = (600,600)
screen = pygame.display.set_mode(size)
pygame.display.set_caption("cindy")

clock = pygame.time.Clock()
 
x = 0
y = 0

done = False
while not done:
    for event in pygame:
        if event.type == pygame.QUIT:
            done = True
        
    key = pygame.key.get_pressed()
        
    if key[pygame.K_LEFT]:
        x-=1
    elif key[pygame.K_RIGHT]:
        x+=1
    elif key[pygame.K_UP]:
        y+=1
    elif key[pygame.K_DOEN]:
        y-=1    
    else:
        pass 
        
    screen.fill(black)
    pygame.draw.circle(screen,colors(),(x,y),50)
 
    pygame.display.flip()
    clock.tick(60)
pygame.quit()