#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov  7 10:15:24 2020

@author: zhuxinyan
"""


import pygame,random

black=(0,0,0)

def colors ():
    r=random .randint(0,255)
    g=random .randint(0,255)
    b=random .randint(0,255)
    return (r,g,b)

size = (600,600)
screen = pygame.display.set_mode(size)
pygame.display.set_caption("cindy")

clock = pygame.time.Clock()
r = 0

click = False
limit = 30
pos = (0,0)

done = False
while not done:
    screen.fill(black)
    
    if click and r < limit:
        pygame.draw.circle(screen,colors(),pos,r)
        r+=1
        if r<=limit:
            click = True
    
    for event in pygame.event.get():
        if event.type == pygame.MOUSEBUTTONDOWN():
            pos = pygame.mouse.get_pos()
            print(pos)

        
        
        
        
        
        
        
        
        
