#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 25 10:14:32 2020

@author: zhuxinyan
"""


fo = open('myfile.txt','w')
fo.write('这是一个测试')

fo = open('myfile.txt','r')
myletter = fo.read()
fo.close()

fo = open('myfile.txt','a')
fo.write('and I')
fo.close()


import os.path

if os.path.isfile('myfile.txt'):
        print('档案存在')
else：
        print('不存在')
    





