#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug  8 10:40:51 2020

@author: zhuxinyan
"""

import time 

run = input("Start > ")

startTime = time.time()
try:
    if run == "start":
        
        while True:
            totalTime = round(time.time() - startTime, 1)
            print(">>>>>>>", totalTime)
            
except KeyboardInterrupt:
    print(totalTime,'seconds')








