#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 30 10:59:54 2020

@author: zhuxinyan
"""


import turtle

canvas=turtle.Screen()
canvas.title('my window')
canvas.bgcolor("green")

alex=turtle.Turtle()
alex.forward(100)
alex.left(90)
alex.forward(100)
alex.left(90)
alex.forward(100)
alex.left(90)
alex.forward(100)

alex.color("bule")
alex.shape("arrow")

turtle.dom()



 