#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 30 12:35:30 2020

@author: zhuxinyan
"""


import turtle

turtle.shape("turtle")
#turtle.penup()#开始画（pen up【不画线】）
size = 20#距离
for i in range(30):#几只（记得加上本体）
    turtle.stamp()#分身显示
    size = size + 10#圈圈变大【距离变远】
    turtle.forward(size)#直走多少
    turtle.right(24)#右转几度
turtle.done()#结束



