#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 13 11:55:08 2020

@author: zhuxinyan
"""


def add3(a,b,c):
    answer = a+b+c
    return answer

a1 = add3(1,2,3)
a2 = add3(3,6,9)
a3 = add3(12,45,78)
print(a1,a2,a3)
