#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun  6 11:12:11 2020

@author: zhuxinyan
"""


scores = []
highest=0
lowest =100
sum=0-

n = input('班上有几人？')

n = int(n)
print(n)

for i in range (n):
    score = input('你的分数')
    score = int(score)
    scores.append(score)

for i in range(n):
    if scores[i] > highest:
        highest = scores[i]
    if scores[i] < lowest:
        lowest = scores[i]
    sum = scores[i] + sum 
average = sum / n

print("平均分：",average)
print("最高分：",highest)
print("最低分：",lowest)






