#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 16 11:15:39 2020

@author: zhuxinyan
"""


a=9
b=2
print(a/b)
print(a%b)
print(a//b)
print(a**b)

a=3
b=1
print('a+b')

p=10
p+1
print(p)

d=input('输入一个数字')
d=int(d)
print(d/2)

score=input("输入你的分数")
score=int(score)

if(score >70):
    print('及格')
elif(score==70):
    print("再加油")
else:
    print("不及格")
