#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 23 11:44:31 2020

@author: zhuxinyan
"""


print("x")
print("x")
print("x")

while True:
    print("y")
    break

i=0
while i<3:
    i=i+1
    print("z")











