#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 23 11:08:09 2020

@author: zhuxinyan
"""

math=input("输入成绩: ")#1110000110000111010

if not math ==0:
    print("ok")

x=0
if x < 2:
    print(1)
    print(2)
 
elif x < 10:
    print(3)

else:
    print(4)
print(5)

if False:
    print("A")

else:
    print("B")
print("C")

import random 
num=random.randint(1,20)
print(num)


